name: "Docker Push"
description: "Perform Docker Push"
inputs:
  image-name:
    description: "Image name"
    required: true
  tag:
    description: "Image tag"
    required: true
  appid:
    description: "Application ID"
    required: true
  orgid:
    description: "Organization ID"
    required: true
  buid:
    description: "Build ID"
    required: true
  role-to-assume:
    description: "Role to assume"
    required: true
  action_type:
    description: "Action type: push or cleanup"
    required: false
    default: "push"
  region:
    description: "Region"
    required: false
    default: "us-east-1"
  # Clean up input
  branch-name:
    description: "Branch name for cleanup filter"
    required: false

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      id: configure-aws
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.region }}
        role-session-name: githubactions-${{ github.run_id }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Push Docker Image to AWS ECR
      if: inputs.action_type == 'push'
      id: push-to-ecr
      shell: bash
      env:
        ORGID: ${{ inputs.orgid }}
        BUID: ${{ inputs.buid }}
        APPID: ${{ inputs.appid }}
        REGION: ${{ inputs.region }}
        TAG: ${{ inputs.tag }}
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_NAME: ${{ inputs.image-name }}

      run: |
        chmod +x ${{ github.action_path }}/scripts/push_docker_to_ecr.sh
        ${{ github.action_path }}/scripts/push_docker_to_ecr.sh

    - name: Cleanup AWS ECR
      if: inputs.action_type == 'cleanup'
      id: cleanup-ecr
      shell: bash
      env:
        ORGID: ${{ inputs.orgid }}
        BUID: ${{ inputs.buid }}
        APPID: ${{ inputs.appid }}
        REGION: ${{ inputs.region }}
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_NAME: ${{ inputs.image-name }}
        BRANCH_NAME: ${{ inputs.branch-name }}
      run: |
        chmod +x ${{ github.action_path }}/scripts/cleanup_ecr.sh
        ${{ github.action_path }}/scripts/cleanup_ecr.sh
